spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

    properties:
      security.protocol: SASL_PLAINTEXT
      sasl.mechanism: PLAIN
      sasl.jaas.config: >
        org.apache.kafka.common.security.plain.PlainLoginModule required
        username="${KAFKA_USERNAME}"
        password="${KAFKA_PASSWORD}";
      schema.registry.url: ${KAFKA_SCHEMA_REGISTRY_URL}
      basic.auth.credentials.source: USER_INFO
      basic.auth.user.info: ${KAFKA_SCHEMA_REGISTRY_USERNAME}:${KAFKA_SCHEMA_REGISTRY_PASSWORD}
      auto.register.schemas: false
      use.latest.version: true

    producer:
      key-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      acks: all
      retries: 3
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
        schema.registry.url: ${KAFKA_SCHEMA_REGISTRY_URL}
        basic.auth.credentials.source: USER_INFO
        basic.auth.user.info: ${KAFKA_SCHEMA_REGISTRY_USERNAME}:${KAFKA_SCHEMA_REGISTRY_PASSWORD}
        auto.register.schemas: false
        use.latest.version: true

    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP}
      auto-offset-reset: earliest
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.key.delegate.class: io.confluent.kafka.serializers.KafkaAvroDeserializer
        spring.deserializer.value.delegate.class: io.confluent.kafka.serializers.KafkaAvroDeserializer
        specific.avro.reader: false
        schema.registry.url: ${KAFKA_SCHEMA_REGISTRY_URL}
        basic.auth.credentials.source: USER_INFO
        basic.auth.user.info: ${KAFKA_SCHEMA_REGISTRY_USERNAME}:${KAFKA_SCHEMA_REGISTRY_PASSWORD}
        auto.register.schemas: false
        use.latest.version: true

server:
  port: 8080

kafka:
  topic: ${KAFKA_TOPIC}

logging:
  level:
    org.apache.kafka: WARN
    com.example.kafkaavro: INFO
